github: [chris-short]
patreon: devopsish
custom: ["paypal.me/devopsish", devopsish.com, chrisshort.net, devopsreadme.com, kubernetesreadme.com, kubenews.net, devopsnewsletters.com, nomedium.dev, padbury.app, crashloopbackoff.dev]